services:
    php:
        image: ${IMAGES_PREFIX:-}app-php
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: frankenphp_prod
        networks:
          - dokploy-network
        environment:
            SERVER_NAME: :80
            SERVER_PORT: 80
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
            MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://localhost/.well-known/mercure}
            MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            SYMFONY_VERSION: ${SYMFONY_VERSION:-}
            STABILITY: ${STABILITY:-stable}
            SYMFONY_TRUSTED_PROXIES: "127.0.0.1,PRIVATE_SUBNETS"
            SYMFONY_TRUSTED_HEADERS: "x-forwarded-for,x-forwarded-host,x-forwarded-proto,x-forwarded-port,x-forwarded-prefix"
        volumes:
            - caddy_data:/data
            - caddy_config:/config          
        extra_hosts:
            - "host.docker.internal:host-gateway"
networks:
  dokploy-network:
    external: true
    
volumes:
    caddy_data:
    caddy_config:
    mysql_data:
    rabbitmq_data:
    ollama:
    manticore_data:
